app:
  scheduler:
    enable: true
    interval: 5000
    force-check-delay: 10s
  database-access-type: jdbc

spring:
  application:
    name: scrapper
  liquibase:
    enabled: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
  default-produces-media-type: application/json
server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
