global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ "localhost:9090" ]
  - job_name: bot
    static_configs:
      - targets: [ "host.docker.internal:8082" ]
  - job_name: scrapper
    static_configs:
      - targets: [ "host.docker.internal:8081" ]
