app:
  telegram-token: 6965503493:AAFSpi1u2oqaLHbpQ9-TTaD7vro60GJ4Aio

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC
springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
  default-produces-media-type: application/json
server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
